language: objective-c
osx_image: xcode7.3

xcode_scheme:
  - skelet

install:
  - brew install node
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - npm config set spin=false
  - npm config set progress=false
  - npm install

script: xctool -project osx/skelet.xcodeproj -scheme "$TRAVIS_XCODE_SCHEME" build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

# enable container-based infrastructure
sudo: false

branches:
  only:
    - master
